import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-dm-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="overflow-hidden container relative mx-auto min-h-screen z-10">
            {children}
          </div>
          <div className="absolute top-0 right-0 z-0">
            <Image
              src="/pattern.png"
              alt=""
              width={0}
              height={0}
              sizes="100vw"
              className="w-full h-full"
            />
          </div>
          <Header />
        </ThemeProvider>
      </body>
    </html>
  );
}
