import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import Image from "next/image";
import Link from "next/link";
import { IconBrandGithub, IconBrandLinkedin } from "@tabler/icons-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-dm-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex items-center justify-end gap-4 p-3">
            <Link
              href={"https://www.linkedin.com/in/hephzibah-oloyede-237b7915b/"}
            >
              <IconBrandLinkedin className="text-primary" />
            </Link>
            <Link href={"https://www.github.com/zibby-zibs"}>
              <IconBrandGithub className="text-primary" />
            </Link>
          </div>
          <div className="overflow-hidden container relative mx-auto min-h-screen z-10">
            {children}
          </div>
          <div className="absolute top-0 right-0 z-0">
            <Image
              src="/pattern.png"
              alt=""
              width={0}
              height={0}
              sizes="100vw"
              className="w-full h-full"
            />
          </div>
          <Header />
        </ThemeProvider>
      </body>
    </html>
  );
}
